### ISSUE TITLE
Give definitions to terms

### ISSUE THREAD

**Issue by DjebbZ** [nayafia/lemonade-stand#12]
It would be nice to give a definition/explain of each method before listing pros/cons. Not everyone is familiar with the wording or the concepts behind. 

Otherwise, great read !

**Comment by nayafia** [comment]
yes! had this in the first draft, but a lot of my definitions felt sort of redundant ("donation button": put a button up to accept donations) so I got rid of them. let me give this another passthrough.

**Comment by nayafia** [comment]
Just added descriptions: https://github.com/nayafia/lemonade-stand/commit/34a312180c7db5c27c5e0d905328cc38f2fc2d94 thanks for the suggestion!

**Comment by DjebbZ** [comment]
I've read it all. Very clear, I learned some stuff in the process. Thank you !
