### ISSUE TITLE
Update Caddy

### ISSUE THREAD

**Issue by mholt** [nayafia/lemonade-stand#136]
Hi, first, I want to say that I have your book and I think it's really great -- thank you for publishing it.

Caddy is currently listed under the "Open Core" section, which was true for a brief time when we tried it, but Caddy's sustainability has largely been met through sponsorships at this point. (Not _sponsorware_, but sponsorships.) A slightly fuller history is explained on Wikipedia: https://en.wikipedia.org/wiki/Caddy_(web_server)

I wonder if we could separate the "Advertising / sponsorships" category into two separate categories. Because although we are funded solely through sponsorships, we do almost no advertising: the sponsorships pay for continued development which is in these professionals' and businesses' best interest. Some businesses also use private support or get development discounts.

I wrote about some of these patterns: https://matt.life/writing/the-asymmetry-of-open-source

How'd you feel if we create a Sponsorships category and move Caddy there?

**Comment by nayafia** [comment]
Hey Matt! Since that category is meant to cover examples of both advertising and sponsorships, I'd just move Caddy from `Open Core` -> `Advertising & sponsorships`, and maybe specify that it's sponsorships only (e.g. list it as `Caddy (sponsorship)`). Feel free to open a PR.
