### ISSUE TITLE
Donating Funds to LemonStand

### ISSUE THREAD

**Issue by Lfada** [nayafia/lemonade-stand#141]
Hi. First thanks for publishing your book, our team is a big fan of your work.  I'm Lucas, a core contributor to the Radworks project. https://radworks.org/

We've been using https://github.com/nayafia/lemonade-stand in many different ways as part of [Drips](http://drips.network/). We consider it one of our most critical dependencies!

We really appreciate the work you all do and we want to make sure that you are all well-funded to keep doing it. For that reason, we have decided to donate some funds to your project through [Drips](https://www.drips.network/) (an initiative that is coming out of our organization for funding FOSS).

We would love to tell you more over a call, or if you prefer via message. Let me know what’s the best channel to discuss this 🙂

**Comment by Lfada** [comment]
Hi @willnorris @mperham @coderberry @andrewtj @nayafia. Who can I talk to about this?

**Comment by nayafia** [comment]
Hi, thanks so much for the kind words, and your interest in supporting this repo! However, I don't need funding support for this project. Feel free to redistribute however you see fit.

**Comment by Lfada** [comment]
thanks for getting back to me @nayafia. We cannot redistribute the funds, unfortunately, but you can still spread the love. If u don’t need the funds pick your critical dependencies and pass it to them with our splitting functionality. 

Here's how you can do it: https://www.youtube.com/watch?v=AOl_XkgWv-A
