### ISSUE TITLE
Open Classifieds

### ISSUE THREAD

**Issue by neo22s** [nayafia/lemonade-stand#18]
Could we add Open-classifieds.com to the showcase?  https://github.com/open-classifieds/openclassifieds2 you can read a bit more about FOSS for profit here too http://open-classifieds.com/2014/02/03/how-we-make-money-open-source-for-profit/

We earn from consultancy, themes and since 1 year ago SaaS https://yclas.com/

thanks

**Comment by nayafia** [comment]
hi! Apologies for the slow response. Which funding category would this best fit into? (Ideally, whichever method is covered most comprehensively in your blog post, so others can learn)

**Comment by neo22s** [comment]
Right now SaaS, but many times we earn from consultancy ;)

**Comment by nayafia** [comment]
ok- this one feels a bit fuzzy to me (ex. in your post you have a section that says "why not SaaS", but you currently earn from SaaS), so I don't think it'll be the most clear-cut example to showcase, especially given that the SaaS category already has a bunch of clearer examples. I appreciate the suggestion though! Apologies this has taken me awhile to resolve. I'm going to close this issue.
