### ISSUE TITLE
SAAS

### ISSUE THREAD

**Issue by millette** [nayafia/lemonade-stand#2]
Offer fremium Software as a service.

**Comment by arikfr** [comment]
Came here to mention this as well. You listed Sentry under the "Open core & paid versions", but I'm not sure it's the same. I might be wrong about Sentry, but I think the hosted version is same as open source. Another example is Ghost.

Also my project, [Redash](https://github.com/getredash/redash), has a similar model -- we have a hosted version which is the same as the open source one. What you pay for is hosting and the fact it's a service.

Maybe it should have a category of its own?

**Comment by aterrel** [comment]
Same as #6? SAAS might be a better term than Hosted.

**Comment by nayafia** [comment]
Should I rename "Managed or hosted services" to SaaS?

**Comment by aterrel** [comment]
yeah that is a more trendy name, although it doesn't include things like "Gitlab on premise". Anaconda Server is another example of an managed open source product. So maybe SaaS / managed is better?

**Comment by aterrel** [comment]
or maybe you are saying its not worth being that granular, which is also a good point for just saying SaaS

**Comment by nayafia** [comment]
yeah, I'll leave it as it is now (SaaS, Open core) unless someone takes issue with it. Thanks so much for clarifying these!
