### ISSUE TITLE
Link for translated page (Chinese)

### ISSUE THREAD

**Issue by wizicer** [nayafia/lemonade-stand#20]
Thanks for your great article, I made a translation to Chinese, if you plan to add link to translated version.
Here is the link: https://github.com/wizicer/FinancialSupportForOpenSource

**Comment by nayafia** [comment]
thanks! this is super awesome and much appreciated 🙌 

I added a link to the translation; if you'd like to add "Chinese" written in its original language (ex. "German (Deutsch)") to the text so it stands out more to those who need it, feel free to submit a PR.
