### ISSUE TITLE
Research experimental "progressive degradation" model of funding

### ISSUE THREAD

**Issue by patcon** [nayafia/lemonade-stand#32]
I can't seem to dig up the source, but at one point (maybe 6-7 years ago) I read a post by someone who had created this really interesting model for funding their service.

Basically, they wrote some glue code that connected their hosting, dns, and bank account in such a way that the costs of the service could be automated paid form the bank account. The interesting bit was that the site monitored the bank account and progressively degraded experience when certain thresholds were not met. The idea was that if people were getting use from the service, and the bank account was running low, they should know that it needed their support, or it would disappear.

In the post, he acknowledged that the site only degraded according to it's financial needs at-cost. But I see no reason why it couldn't also work while taking into account a desired "budget" of the creator. So if they feel that they should be able to make $200 off the site per month, they could be transparent about that. And paying them out as creator each month could be factored into the costs of running the site. If the hosting + dns + cost of living of the creator are not met, features start to be disabled progressively.

I think about this model a lot, and it's on my back-burner to someday create a framework for facilitating this. Right now, there is perhaps not enough primary resources to include this here, but I'm hoping that someone remembers that post, and can help me dredge it up :)

**Comment by nayafia** [comment]
Ha! That's a fascinating idea. I haven't heard about it, but if anyone else is able to dig up the source, would love to read. Feels like we could do a thread/category just for experimental ideas.
