### ISSUE TITLE
Terry Lambert - Apple Core OS Kernel Team; technical lead on several projects over 8 years

### ISSUE THREAD

**Issue by ktsaou** [nayafia/lemonade-stand#33]
I found this view of Terry Lambert - Apple Core OS Kernel Team; technical lead on several projects over 8 years:

https://www.quora.com/How-should-open-source-programmers-make-money/answer/Terry-Lambert

His response on "how to make money from open-source" is quite interesting...

**Comment by nayafia** [comment]
Thanks, there's some fascinating history in here! Closing because this isn't actionable, but appreciate the link.
