### ISSUE TITLE
Collecting Bitcoins via FOSS License Aggregation

### ISSUE THREAD

**Issue by jhabdas** [nayafia/lemonade-stand#47]
Idea here change from using referral links to collect Bitcoins to provide a bigger vision whereby the FOSS community creates crypto-licenses and companies using FOSS software of a large enough size or market cap are required to pay licensing fees to open source developers but the little guys get to ride for free so they can't have a chance of competing.

**Comment by jhabdas** [comment]
https://medium.com/@jhabdas/introducing-the-btc-license-28650887eb11

Submitted request to add BTC License to SPDX though a new copyright pseudo-format may be more appropriate for wallet sharing in crypto licenses. I've also submitted a support request to GitHub to allow `bitcoin` scheme to README files referencing [BIP-0021](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki).

**Comment by jhabdas** [comment]
After discussing with SPDX they suggested a license would need to have traction in the community to make it—same with the OSI I believe. Of course doing that without an ICO could be challenging. May need to get creative here. Anyone have any product ideas which could move something like this forward?

Ultimately what I'd like to see is a set of licenses which allow public corporations using open source software to donate back to the developers by recognizing them via the addresses in their licenses.

Oh, and here's a related post about the BTC License thanks to Black Duck:
blog.blackducksoftware.com/can-blockchain-btc-license-fund-health-insurance

**Comment by nayafia** [comment]
Closing as I don't think there's anything actionable here re: this repo - thanks for flagging the BTC License!

**Comment by jhabdas** [comment]
@nayafia thanks. this of course is a new model never attempted in open source software. if you have any constructive suggestions on what can be done to make it actionable that would be useful considering the time spent to built the concept.

note however due to BTC blocksize limitations the BTC license will be changing to BCH.
