### ISSUE TITLE
Code Sponsor

### ISSUE THREAD

**Issue by cavneb** [nayafia/lemonade-stand#51]
Hi @nayafia .. would you mind adding Code Sponsor to this list?

**Comment by nayafia** [comment]
Thanks! I was going to do this anyway, so thank you for the reminder :) Can you open a PR that links to Code Sponsor under https://github.com/nayafia/lemonade-stand#advertising--sponsorships - "case studies" section?

**Comment by cavneb** [comment]
@nayafia https://github.com/nayafia/lemonade-stand/pull/53

Thanks!

**Comment by nayafia** [comment]
Closed via #53.
