### ISSUE TITLE
Graitpay is shutting down

### ISSUE THREAD

**Issue by aggsol** [nayafia/lemonade-stand#57]
Liberapay (https://liberapay.com/) is a worthy replacement.

**Comment by EdOverflow** [comment]
@aggsol: There is a typo in your title. You are referring to "Gratipay". 

The announcement can be found here: https://gratipay.news/the-end-cbfba8f50981.

**Comment by nayafia** [comment]
Thanks @aggsol! This should be covered by https://github.com/nayafia/lemonade-stand/pull/56 (both removal and Liberapay replacement).
