### ISSUE TITLE
Awesome research, reductive name

### ISSUE THREAD

**Issue by sscarduzio** [nayafia/lemonade-stand#67]
This repo is something I really needed  one year ago when I was conceptualising the business model behind my side project [ReadonlyREST](https://readonlyrest.com), which soon became my day job.

I tried to put together a similar research, but this is much better and more complete. So big thank you for publishing it!

The only thing that doesn't sound ok is the name of the repo, OSS is not just "lemonade stand" material. Like the doc shows and demonstrates via the case studies cited, OSS is a very solid business strategy in so many ways.

What do you think?

**Comment by danielskatz** [comment]
FWIW, I tried to take this and create a version more focused on how to fund project, and less on how to fund individuals: https://github.com/danielskatz/sustaining-research-projects

**Comment by nayafia** [comment]
Hey @sscarduzio! Thanks for the kind words. I admit I was trying to get cheeky with the name - I'm usually a terrible, extremely literal namer of things (see https://github.com/nayafia/contributing-template, https://github.com/github/opensource.guide, https://github.com/maintainers 😄 ), and I had a rare moment of inspiration on this one. The name also reflects that when I originally published this repo, I didn't expect anyone to even find it interesting or useful. It was, and is still meant to be, a simple list of things I noticed people were doing, without making judgment on which of those methods is best. It's a reference guide, not an advocacy document.

In retrospect, I understand that the name seems a bit reductive. Open source isn't charity, it's a critical service, and I think a long-term sustainable solution will require a serious, coordinated investment into digital infrastructure. But hopefully the content of this repo, which touches on everything from SaaS to venture capital, demonstrates that there's much more to it than tipping.

Thanks for sharing your feedback!
