### ISSUE TITLE
Qt

### ISSUE THREAD

**Issue by y2kbugger** [nayafia/lemonade-stand#68]
I think it's a bit of a stretch to call SQLite dual license. They will sell you "license" as in a proof of purchase but the code is always licensed under the public domain.

QT is an example of something that is genuinely dual license.

**Comment by nayafia** [comment]
Hey @y2kbugger! I like that SQLite is a creative implementation of dual license, especially because they sell the "official" license. QT is a good example too, though, that showcases a different implementation. Feel free to open a PR to add it to the list :)
