### ISSUE TITLE
Tagline suggestion

### ISSUE THREAD

**Issue by kennethreitz** [nayafia/lemonade-stand#7]
The current tagline, in my option, leaves something to be desired. I won't go into detail, so I'll share my alternative.

From: "a handy guide to making money in open source"

To : "a handy guide to financial sustainability for open source projects"

... or something along those lines.

**Comment by nayafia** [comment]
thanks! you're right, it's a subpar choice of words.

my issue with "financial sustainability" is that sustainability to me implies a secure, renewing, recurring source of revenue (however one makes that work). A lot of the suggestions in this guide are actually not proven out or sustainable; it's simply a brain dump of every way I know of that people have made more than $0 contributing to open source.

would "a handy guide to finding $$ in open source" be better? "Finding funding"?

**Comment by kennethreitz** [comment]
Hmm, "financial support"?

**Comment by nayafia** [comment]
👍  that's great! updated. thank you!
