### ISSUE TITLE
category sell  licenses for professional use 

### ISSUE THREAD

**Issue by aberlin** [nayafia/lemonade-stand#9]
this is maybe a new category: sell  licenses for professional use 
**Pros**
whole code is freely available 

**cons**
probably a lot of scary unhandy legal stuff 
[Osirix](http://www.osirix-viewer.com/Store.html)
[Redhat](http://www.redhat.com/licenses/ccmpl.html)
[Owncloud](https://owncloud.org/contribute/agreement/)
[Some on this list have this approach](https://en.wikipedia.org/wiki/Contributor_License_Agreement)

**Comment by kennethreitz** [comment]
Dual license of GPL + Commercial (for $) is common.

**Comment by nayafia** [comment]
hmm. is this covered by the "open core" category, or can it be rolled in somehow? what do you think?

**Comment by kennethreitz** [comment]
@nayafia sometimes the commercial version is identical to the open source (GPL) version, however, without the GPL (which companies can't use if they're shipping the code due to its virality).

**Comment by shaunagm** [comment]
I don't believe Red Hat has dual licensed products?  [MySQL](http://www.mysql.com/about/legal/licensing/oem/) is dual licensed, though.

**Comment by aberlin** [comment]
I think it is not really covered by "open core" category because the whole code is free. It would be more a "Consulting & services" but without consulting and service. 
Also the "sell licenses " category is more divers because on the one hand side there is the dual licensing, but on the other hand there is professional licensing(for medicine or heavy machinery) which doesn't really fit as consulting or extra service because the project focus is still on the code.  I think for the second case [Osirix](http://www.osirix-viewer.com/Store.html) is still the best case study I find but there are probably a lot more cases where the user needs a label for legal reasons and can not really work professional with plain GPL.

**Comment by emaste** [comment]
I think it is distinct from open core. Copyleft (GPL/LGPL) with an option for a closed-source license is a fairly common case as mentioned above. SQLite is also in this "sell optional license" category as a very interesting example: it's public domain, but users can pay $6000 for an explicit license - see https://www.sqlite.org/copyright.html

**Comment by nayafia** [comment]
Just added this category: https://github.com/nayafia/lemonade-stand/commit/6ccb0282d899686727bbd2026d8f175fce5c86c0 Thanks all for your help!

**Comment by emaste** [comment]
Thanks!
