### ISSUE TITLE
Missing pay-what-you-want model

### ISSUE THREAD

**Issue by 12people** [nayafia/lemonade-stand#99]
Scanning through your list, it seems as though you left out a pay-what-you-want business model, which elementaryOS uses both for its OS and for apps in its AppCenter: https://medium.com/elementaryos/building-the-future-of-elementary-os-9df3fa940b67 .

**Comment by nayafia** [comment]
I'd consider this part of the donations category; feel free to open a PR to add it as a case study there, if you'd like!
